# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [ master ]   # Change to 'main' if your default branch is 'main'
  pull_request:
    branches: [ master ]   # Change to 'main' if your default branch is 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Generate gRPC Python Files
      run: |
        python -m grpc_tools.protoc -I./backend/proto --python_out=./backend/app --grpc_python_out=./backend/app ./backend/proto/form_processor.proto

    - name: Install Testing and Linting Tools
      run: |
        pip install pytest pytest-cov flake8

    - name: Run Tests with Coverage
      run: |
        pytest --cov=backend/app --cov-report=xml backend/tests/

    - name: Run Flake8 Linting
      run: |
        flake8 backend/app backend/tests

    - name: Upload Coverage XML Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-xml
        path: coverage.xml

    - name: Upload HTML Coverage Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-html
        path: htmlcov/
