# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import form_processor_pb2 as form__processor__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in form_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FormProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessForm = channel.unary_unary(
                '/formprocessor.FormProcessor/ProcessForm',
                request_serializer=form__processor__pb2.FormData.SerializeToString,
                response_deserializer=form__processor__pb2.FormResponse.FromString,
                _registered_method=True)


class FormProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessForm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FormProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessForm': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessForm,
                    request_deserializer=form__processor__pb2.FormData.FromString,
                    response_serializer=form__processor__pb2.FormResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'formprocessor.FormProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('formprocessor.FormProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FormProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessForm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/formprocessor.FormProcessor/ProcessForm',
            form__processor__pb2.FormData.SerializeToString,
            form__processor__pb2.FormResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
