# backend/.github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate gRPC Python Files
      run: |
        python -m grpc_tools.protoc -I./proto --python_out=./app --grpc_python_out=./app ./proto/form_processor.proto

    - name: Run tests with coverage
      run: |
        pip install pytest-cov
        pytest --cov=app --cov-report=xml tests/

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Upload HTML Coverage Report as Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: html-coverage-report
        path: htmlcov/
