name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.12] # Only valid Python versions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Remove old Python version caches to prevent issues
      - name: Remove Python Caches
        run: sudo rm -rf /opt/hostedtoolcache/Python/3.1*

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Generate gRPC Python Files
        run: |
          python -m grpc_tools.protoc \
          -I./backend/proto \
          --python_out=./backend/app \
          --grpc_python_out=./backend/app \
          --proto_path=./backend/proto \
          --descriptor_set_out=backend/app/form_processor.descriptor \
          -Mform_processor.proto=app.form_processor_pb2 \
          ./backend/proto/form_processor.proto

      - name: Run Tests with Coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=backend/app --cov-report=xml backend/tests/

      - name: Upload Coverage XML Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-xml
          path: coverage.xml

      - name: Upload HTML Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-html
          path: htmlcov/
